services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
    ports:
      - "5000:5000" 

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--entrypoints.http.address=:8080" 
      - "--providers.file.filename=/etc/traefik/traefik.yml"
      - "--api.insecure=true"
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock